clear_usercode:
  description: Clear a usercode from lock

  fields:
    node_id:
      description: Node id of the lock
      example: 18
    code_slot:
      description: Code slot to clear code from
      example: 1

get_usercode:
  description: Retrieve a usercode from lock

  fields:
    node_id:
      description: Node id of the lock
      example: 18
    code_slot:
      description: Code slot to retrive a code from
      example: 1

lock:
  description: Lock all or specified locks

  fields:
    entity_id:
      description: Name of lock to lock
      example: 'lock.front_door'
    code:
      description: An optional code to lock the lock with
      example: 1234

set_usercode:
  description: Set a usercode to lock

  fields:
    node_id:
      description: Node id of the lock
      example: 18
    code_slot:
      description: Code slot to set the code
      example: 1
    usercode:
      description: Code to set
      example: 1234

unlock:
  description: Unlock all or specified locks

  fields:
    entity_id:
      description: Name of lock to unlock
      example: 'lock.front_door'
    code:
      description: An optional code to unlock the lock with
      example: 1234

wink_set_lock_vacation_mode:
  description: Set vacation mode for all or specified locks. Disables all user codes.

  fields:
    entity_id:
      description: Name of lock to unlock
      example: 'lock.front_door'
    enabled:
      description: enable or disable. true or false. 
      example: true

wink_set_lock_alarm_mode:
  description: Set alarm mode for all or specified locks.

  fields:
    entity_id:
      description: Name of lock to unlock
      example: 'lock.front_door'
    mode:
      description: One of tamper, activity, or forced_entry 
      example: tamper

wink_set_lock_alarm_sensitivity:
  description: Set alarm sensitivity for all or specified locks.

  fields:
    entity_id:
      description: Name of lock to unlock
      example: 'lock.front_door'
    sensitivity:
      description: One of low, medium_low, medium, medium_high, high 
      example: medium

wink_set_lock_alarm_state:
  description: Set alarm state.

  fields:
    entity_id:
      description: Name of lock to unlock
      example: 'lock.front_door'
    enabled:
      description: enable or disable. true or false. 
      example: true

wink_set_lock_beeper_state:
  description: Set beeper state.

  fields:
    entity_id:
      description: Name of lock to unlock
      example: 'lock.front_door'
    enabled:
      description: enable or disable. true or false. 
      example: true

