  >
  "杨金
  {% if now().strftime("%H")|int < 12 %}
  早上好。
  {% elif now().strftime("%H")|int < 18 %}
  下午好。
  {% else %}
  晚上好。
  {% endif %}
  现在成都的天气为,
  {% if is_state('sensor.dark_sky_summary', 'Clear') %}
  晴
  {% elif is_state('sensor.dark_sky_summary', 'Partly Cloudy') %}
  多云
  {% elif is_state('sensor.dark_sky_summary', 'Overcast') %}
  阴
  {% elif is_state('sensor.dark_sky_summary', 'Light Rain') %}
  小雨
  {% elif is_state('sensor.dark_sky_summary', 'Rain') %}
  雨
  {% elif is_state('sensor.dark_sky_summary', 'Heavy Rain') %}
  大雨
  {% else %}
  {{states('sensor.dark_sky_summary')}},
  {% endif %}
  ,
  当前温度为{{states('sensor.dark_sky_temperature')}}度,
  预计今天的最高温度为{{states('sensor.dark_sky_daily_high_temperature')}}度,
  最低温度为{{states('sensor.dark_sky_daily_low_temperature')}}度,
  PM2.5指数为{{states('sensor.waqi_chengdu')}}
  {% if states.sensor.waqi_chengdu.state|int <= 50 %}
  优
  {% elif states.sensor.waqi_chengdu.state|int <= 100 %}
  良
  {% elif states.sensor.waqi_chengdu.state|int <= 150 %}
  轻度污染，儿童、老年人及心脏病、呼吸系统疾病患者应减少长时间、高强度的户外锻炼
  {% elif states.sensor.waqi_chengdu.state|int <= 200 %}
  中度污染，儿童、老年人及心脏病、呼吸系统疾病患者避免长时间、高强度的户外锻炼，一般人群适量减少户外运动
  {% elif states.sensor.waqi_chengdu.state|int <= 300 %}
  重度污染，儿童、老年人及心脏病、肺病患者应停留在室内，停止户外运动，一般人群减少户外运动
  {% elif states.sensor.waqi_chengdu.state|int > 300 %}
  严重污染，儿童、老年人和病人应停留在室内，避免体力消耗，一般人群避免户外活动
  {% endif %}"
