foursquare:
  checkin:
    description: Check a user into a Foursquare venue

    fields:
      venueId:
        description: The Foursquare venue where the user is checking in. [Required]
        example: IHR8THISVNU

      eventId:
        description: The event the user is checking in to. [Optional]
        example: UHR8THISVNT

      shout:
        description: A message about your check-in. The maximum length of this field is 140 characters. [Optional]
        example: There are crayons! Crayons!

      mentions:
        description: Mentions in your check-in. This parameter is a semicolon-delimited list of mentions. A single mention is of the form "start,end,userid", where start is the index of the first character in the shout representing the mention, end is the index of the first character in the shout after the mention, and userid is the userid of the user being mentioned. If userid is prefixed with "fbu-", this indicates a Facebook userid that is being mention. Character indices in shouts are 0-based. [Optional]
        example: 5,10,HZXXY3Y;15,20,GZYYZ3Z;25,30,fbu-GZXY13Y

      broadcast:
        description: "Who to broadcast this check-in to. Accepts a comma-delimited list of values: private (off the grid) or public (share with friends), facebook share on facebook, twitter share on twitter, followers share with followers (celebrity mode users only), If no valid value is found, the default is public. [Optional]"
        example: public,twitter

      ll:
        description: Latitude and longitude of the user's location. Only specify this field if you have a GPS or other device reported location for the user at the time of check-in. [Optional]
        example: 33.7,44.2

      llAcc:
        description: Accuracy of the user's latitude and longitude, in meters. [Optional]
        example: 1

      alt:
        description: Altitude of the user's location, in meters. [Optional]
        example: 0

      altAcc:
        description: Vertical accuracy of the user's location, in meters.
        example: 1

group:
  reload:
    description: "Reload group configuration."
    fields:

  set_visibility:
    description: Hide or show a group

    fields:
      entity_id:
        description: Name(s) of entities to set value
        example: 'group.travel'

      visible:
        description: True if group should be shown or False if it should be hidden.
        example: True

persistent_notification:
  create:
    description: Show a notification in the frontend

    fields:
      message:
        description: Message body of the notification. [Templates accepted]
        example: Please check your configuration.yaml.

      title:
        description: Optional title for your notification. [Optional, Templates accepted]
        example: Test notification

      notification_id:
        description: Target ID of the notification, will replace a notification with the same Id. [Optional]
        example: 1234

homematic:
  virtualkey:
    description: Press a virtual key from CCU/Homegear or simulate keypress

    fields:
      address:
        description: Address of homematic device or BidCoS-RF for virtual remote
        example: BidCoS-RF

      channel:
        description: Channel for calling a keypress
        example: 1

      param:
        description: Event to send i.e. PRESS_LONG, PRESS_SHORT
        example: PRESS_LONG

      proxy:
        description: (Optional) for set a hosts value
        example: Hosts name from config

  set_var_value:
    description: Set the name of a node.

    fields:
      entity_id:
        description: Name(s) of homematic central to set value
        example: 'homematic.ccu2'

      name:
        description: Name of the varaible to set
        example: 'testvariable'

      value:
        description: New value
        example: 1

  set_dev_value:
    description: Set a device property on RPC XML inteface.

    fields:
      address:
        description: Address of homematic device or BidCoS-RF for virtual remote
        example: BidCoS-RF

      channel:
        description: Channel for calling a keypress
        example: 1

      param:
        description: Event to send i.e. PRESS_LONG, PRESS_SHORT
        example: PRESS_LONG

      proxy:
        description: (Optional) for set a hosts value
        example: Hosts name from config

      value:
        description: New value
        example: 1

  reconnect:
    description: Reconnect to all Homematic Hubs.

microsoft_face:
  create_group:
    description: Create a new person group.

    fields:
      name:
        description: Name of the group
        example: 'family'

  delete_group:
    description: Delete a new person group.

    fields:
      name:
        description: Name of the group
        example: 'family'

  train_group:
    description: Train a person group.

    fields:
      group:
        description: Name of the group
        example: 'family'

  create_person:
    description: Create a new person in the group.

    fields:
      name:
        description: Name of the person
        example: 'Hans'

      group:
        description: Name of the group
        example: 'family'

  delete_person:
    description: Delete a person in the group.

    fields:
      name:
        description: Name of the person
        example: 'Hans'

      group:
        description: Name of the group
        example: 'family'

  face_person:
    description: Add a new picture to a person.

    fields:
      person:
        description: Name of the person
        example: 'Hans'

      group:
        description: Name of the group
        example: 'family'

      camera_entity:
        description: Camera to take a picture
        example: camera.door

verisure:
  capture_smartcam:
    description: Capture a new image from a smartcam.

    fields:
      device_serial:
        description: The serial number of the smartcam you want to capture an image from.
        example: '2DEU AT5Z'

alert:
  turn_off:
    description: Silence alert's notifications.

    fields:
      entity_id:
        description: Name of the alert to silence.
        example: 'alert.garage_door_open'

  turn_on:
    description: Reset alert's notifications.

    fields:
      entity_id:
        description: Name of the alert to reset.
        example: 'alert.garage_door_open'

  toggle:
    description: Toggle alert's notifications.

    fields:
      entity_id:
        description: Name of the alert to toggle.
        example: 'alert.garage_door_open'

hdmi_cec:
  send_command:
    description: Sends CEC command into HDMI CEC capable adapter.

    fields:
      raw:
        description: 'Raw CEC command in format "00:00:00:00" where first two digits are source and destination, second byte is command and optional other bytes are command parameters. If raw command specified, other params are ignored.'
        example: '"10:36"'

      src:
        desctiption: 'Source of command. Could be decimal number or string with hexadeximal notation: "0x10".'
        example: '12 or "0xc"'

      dst:
        description: 'Destination for command. Could be decimal number or string with hexadeximal notation: "0x10".'
        example: '5 or "0x5"'

      cmd:
        description: 'Command itself. Could be decimal number or string with hexadeximal notation: "0x10".'
        example: '144 or "0x90"'

      att:
        description: Optional parameters.
        example: [0, 2]

  update:
    description: Update devices state from network.

  volume:
    description: Increase or decrease volume of system.

    fields:
      up:
        description: Increases volume x levels.
        example: 3
      down:
        description: Decreases volume x levels.
        example: 3
      mute:
        description: Mutes audio system. Value should be on, off or toggle.
        example: "toggle"

  select_device:
    description: Select HDMI device.
    fields:
      device:
        description: Addres of device to select. Can be entity_id, physical address or alias from confuguration.
        example: '"switch.hdmi_1" or "1.1.0.0" or "01:10"'

  power_on:
    description: Power on all devices which supports it.

  standby:
    description: Standby all devices which supports it.

ffmpeg:
  start:
    description: Send a start command to a ffmpeg based sensor.
    fields:
      entity_id:
        description: Name(s) of entites that will start. Platform dependent.
        example: 'binary_sensor.ffmpeg_noise'

  stop:
    description: Send a stop command to a ffmpeg based sensor.
    fields:
      entity_id:
        description: Name(s) of entites that will stop. Platform dependent.
        example: 'binary_sensor.ffmpeg_noise'

  restart:
    description: Send a restart command to a ffmpeg based sensor.
    fields:
      entity_id:
        description: Name(s) of entites that will restart. Platform dependent.
        example: 'binary_sensor.ffmpeg_noise'

logger:
  set_level:
    description: Set log level for components.

hassio:
  host_reboot:
    description: Reboot host computer.

  host_shutdown:
    description: Poweroff host computer.

  host_update:
    description: Update host computer.
    fields:
      version:
        description: Optional or it will be use the latest version.
        example: '0.3'

  supervisor_update:
    description: Update HassIO supervisor.
    fields:
      version:
        description: Optional or it will be use the latest version.
        example: '0.3'

  supervisor_reload:
    description: Reload HassIO supervisor addons/updates/configs.

  homeassistant_update:
    description: Update HomeAssistant docker image.
    fields:
      version:
        description: Optional or it will be use the latest version.
        example: '0.40.1'

  addon_install:
    description: Install a HassIO docker addon.
    fields:
      addon:
        description: Name of addon.
        example: 'smb_config'
      version:
        description: Optional or it will be use the latest version.
        example: '0.2'

  addon_uninstall:
    description: Uninstall a HassIO docker addon.
    fields:
      addon:
        description: Name of addon.
        example: 'smb_config'

  addon_update:
    description: Update a HassIO docker addon.
    fields:
      addon:
        description: Name of addon.
        example: 'smb_config'
      version:
        description: Optional or it will be use the latest version.
        example: '0.2'

  addon_start:
    description: Start a HassIO docker addon.
    fields:
      addon:
        description: Name of addon.
        example: 'smb_config'

  addon_stop:
    description: Stop a HassIO docker addon.
    fields:
      addon:
        description: Name of addon.
        example: 'smb_config'

eight_sleep:
  heat_set:
    description: Set heating level for eight sleep.
    fields:
      entity_id:
        description: Entity id of the bed state to adjust.
        example: 'sensor.eight_left_bed_state'
      target:
        description: Target heating level from 0-100.
        example: 35
      duration:
        description: Duration to heat at the target level in seconds.
        example: 3600
