- alias: weather
  initial_state: true
  trigger:
    platform: state
    entity_id: switch.weather
    to: 'on'
  action:
    - service: shell_command.weather
#    - service: notify.instapush
#      data_template: 
#        title: "Weather"
#        message:  
#          !include messages/message_weather.yaml
    - service: notify.ios_yangjin
      data:
        message:  
          !include messages/message_weather.yaml
        data:
          push:
            sound: "US-EN-Alexa-Good-Morning.wav"

- alias: music
  initial_state: true
  trigger:
    platform: event
    event_type: call_service
    event_data:
      domain: media_player
      service: media_play
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.music
        volume_level: 0.6
    - service: media_player.play_media
      data:
        entity_id: media_player.music
        media_content_id: /config/test1.mp3
        media_content_type: 'music'
    - service: automation.turn_off
      data:
        entity_id: automation.music
