homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 30.6667
  longitude: 104.0667
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 498
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
  - platform: broadlink
    host: 192.168.3.16
    mac: '34:EA:34:E9:B8:23'
    monitored_conditions:
      - 'temperature'

# Text to speech
tts:
  platform: google

group: !include groups.yaml
#automation: !include automations.yaml

light:
  - platform: yeelight
    devices:
      192.168.3.3:
        name: light

switch:
  platform: broadlink
  host: 192.168.3.16
  mac: '34:EA:34:E9:B8:23'
  switches:
    officetv:
      friendly_name: "officeTV"
      command_on: 'JgDgAFASKBIVEywOGA8pEhUSFRIpEhUSGg0YEBUAA0lUDiwPFRIpEhUSKBMVEhgPKBMUExUSFRIVAANKTxMoEhUSLA8VEiwPFRIVEikSFRIVEhUSFQADSlMPLA8UEygTFBMoEhUTGA8oEhUTFBMUExUAA0pOFCcTFBMsDxQTKBMUExQTKBMUExUSFRIVAANKUBIoExUSKBMUEygSFRMYDygSFRMUExUSFQADSk8SKRIVEikSFRIpEhgPFRIpEhUSFRIZDhUAA0pQEigTGA8oEhUSKRIVEhkOLg0VEhUSFRMVAA0FAAAAAAAAAAA='
      command_off: 'JgDgAFASKBIVEywOGA8pEhUSFRIpEhUSGg0YEBUAA0lUDiwPFRIpEhUSKBMVEhgPKBMUExUSFRIVAANKTxMoEhUSLA8VEiwPFRIVEikSFRIVEhUSFQADSlMPLA8UEygTFBMoEhUTGA8oEhUTFBMUExUAA0pOFCcTFBMsDxQTKBMUExQTKBMUExUSFRIVAANKUBIoExUSKBMUEygSFRMYDygSFRMUExUSFQADSk8SKRIVEikSFRIpEhgPFRIpEhUSFRIZDhUAA0pQEigTGA8oEhUSKRIVEhkOLg0VEhUSFRMVAA0FAAAAAAAAAAA='
    livingac:
      friendly_name: "LivingroomAirCon"
      command_on: 'JgDMAHNyHVUeHB0cHB4eVR0cHR0bVx5VHRweHBweHVUeHRweHFUeVR1VHhwdHhxVHVUeHB0fG1UeVR0cHhweVB5VHR0bHnNyHVUeHB0cHhweVR0cHh0cVR5VHRweHBweHFYeHB0cHlUeVR1VHhwdHR1VHlUdHBwgG1UeVR0cHhweVR1VHhwdHHNwIFQeHB4cHRweVR0dHRwcVx1VHB4dHB4cHlQeHhwcHVYdVR5VHRwdHR1VHlUdHBweHlUdUx4eHRweVR1VHhwdHXNxHQANBQAAAAAAAAAAAAAAAA=='
      command_off: 'JgDMAHNyHVUeHB0cHB4eVR0cHR0bVx5VHRweHBweHVUeHRweHFUeVR1VHhwdHhxVHVUeHB0fG1UeVR0cHhweVB5VHR0bHnNyHVUeHB0cHhweVR0cHh0cVR5VHRweHBweHFYeHB0cHlUeVR1VHhwdHR1VHlUdHBwgG1UeVR0cHhweVR1VHhwdHHNwIFQeHB4cHRweVR0dHRwcVx1VHB4dHB4cHlQeHhwcHVYdVR5VHRwdHR1VHlUdHBweHlUdUx4eHRweVR1VHhwdHXNxHQANBQAAAAAAAAAAAAAAAA=='
    livingtv:
      friendly_name: "LivingroomTV"
      command_on: 'JgBWAJORExITNhQ2EzcTEhMSExITEhMSFDUUNhQ1FRAVEBUQFRAVEBUQFTUUNRUQFRAVEBUQFTUUNRURFBAVNRU1FDUVNRQABe=='
      command_off: 'JgBWAJORExITNhQ2EzcTEhMSExITEhMSFDUUNhQ1FRAVEBUQFRAVEBUQFTUUNRUQFRAVEBUQFTUUNRURFBAVNRU1FDUVNRQABe=='
    bedroomac:
      friendly_name: "BedroomAirCon"
      command_on: 'JgC8AXI6DQ8OKg0PDg8NDw0QDQ8NEA0QDQ8NDw4PDQ8OKg0PDg8ODw0PDRANDw0QDSoNKw0rDQ8ODw0qDg8NDw4PDQ8NEA0QDQ8NEA0PDQ8ODw0PDg8NEA0PDRANDw0PDg8NDw4PDg8NDw0QDQ8NEA0PDQ8ODw4PDSoOKg0QDQ8NDw4PDQ8OAAFHcToODw0rDQ8NEA0PDQ8ODw0QDQ8NEA0PDRANDw0rDQ8NEA0PDg8NDw4PDQ8NKw0rDSsNDw0QDSoNEA0PDRANDw0QDQ8ODw0PDRANDw0QDQ8NEA0rDQ8NDw4PDQ8ODw0PDRANEA0PDSsNDw0rDSoODw0QDQ8NEA0PDRANDw0PDg8NKw0PDg8NKw0PDSsOKQ4PDRANDw0QDQ8NDw4PDQ8PDg0QDQ8NEA0PDRANDw0PDg8NEA0PDSsNKg4PDQ8ODw0PDg8NEA0PDRANDw0PDykNKw0QDQ8NEA0PDQ8ODw0qDg8NEA0PDg8ODg0QDQ8NEA4ODg8NDw8ODg4PDg4ODg8ODg4qDg8ODg4ODw4ODg8ODg4PDg8ODikPKQ4ODw4ODg8ODg8OKQ8pDg4PKQ4qDikPKQ4qDgANBQAAAAAAAAAAAAAAAA=='
      command_off: 'JgC8AXQ4Dw0QKA8NEA0PDRANDw0QDQ8NEA0PDRANDw0QKA8NEA0QDQ8NEA0PDRAMECgQKA8pDw0QDQ8oEA0PDRANDw0QDRANDw0QDBANDw0QDQ8NEA0QDQ8NEA0PDRAMEA0PDRANEA0PDRANDw0QDBANDw0QDRANDygQKBAMEA0PDRANDw0QAAFFcToODw0rDQ8NDw4PDQ8ODw0QDQ8ODw8NDw4PDQ8pEAwPDg8NEA0PDw4NDw0QKA8oECkPDQ8NECgPDg8NDw0QDQ8ODw0ODw0PDRANDw0PDg8NEA0PDg8NDw4PDQ8NEA0PDRANDw4PDSoODw0rDSoODw0QDQ8NDw4PDQ8ODw0PDg8NKw4ODg8NKg4PDSoPKQ0PDg8ODw0PDg8NDw4PDQ8NEA0PDg8NDw4PDQ8ODw0PDRANEA0PDSsNKg4PDQ8NEA0PDRANDw4PDQ8ODw0PDioNKg4PDg8NDw4PDQ8NEA0qDg8NEA0PDQ8ODw0PDg8NDw4PDRANDw0QDQ8NDw4PDQ8ODw0rDQ8ODw0PDg8NDw0QDQ8NEA0PDioNKw0PDw4NDw0PDg8ODw0qEA0PKQ8oDykPKBAoEAANBQAAAAAAAAAAAAAAAA=='
    bedroomtv:
      friendly_name: "BedroomTV"
      command_on: 'JgBmAJSPFBAVNRQ1FDUVEBQRFBEUERQQFTUUNRQ1FRAUERQRFBAVEBUQFDUVNBUQFRAVEBQRFDUVNBUQFRAUNRU1FDUUNRQABemUjxQ1FQAMOJSPFDUVAAw4lI8UNRUADDiTkBM2EwANBQAA'
      command_off: 'JgBmAJSPFBAVNRQ1FDUVEBQRFBEUERQQFTUUNRQ1FRAUERQRFBAVEBUQFDUVNBUQFRAVEBQRFDUVNBUQFRAUNRU1FDUUNRQABemUjxQ1FQAMOJSPFDUVAAw4lI8UNRUADDiTkBM2EwANBQAA'
    yacoolstore:
      friendly_name: "GAOYONG stero"
      command_on: 'JgBYAAABKZMUERQRFRETNhU1FTYTNxQRExIUNhQ2FDYUERQRFBEUERUQFBEUERURExEVEBURExEVNhQ2FDYUNhQ2FDYVNRQ2FQAFRgABKkgVAAxeAAEnSxIADQU=' 
      command_off: 'JgBYAAABKpIUERUQFBITNhQ2FTYUNhMSFBAVNhQ2EzcUERMSFBEVEBMTExEVEBQSExEVEBQSFBAVNhQ2EzYVNhQ2EzcUNhQ2FAAFRwABKkgVAAxdAAEqSBUADQU='

media_player:
    - platform: vlc
      name: speaker

automation:
  - alias: play music
    trigger:
      platform: event
      event_type: call_service
      event_data:
        domain: media_player
        service: media_play
    action:
      service: media_player.play_media
      data:
        media_content_id: 'mms://radio.mx8087.cn/tingmx'
        media_content_type: 'music'
