- platform: broadlink
  host: 192.168.3.16
  mac: '34:EA:34:E9:B8:23'
  switches:
    bedroomac:
      friendly_name: "BedroomAirCon"
      command_on: 'JgC8AXI6DQ8OKg0PDg8NDw0QDQ8NEA0QDQ8NDw4PDQ8OKg0PDg8ODw0PDRANDw0QDSoNKw0rDQ8ODw0qDg8NDw4PDQ8NEA0QDQ8NEA0PDQ8ODw0PDg8NEA0PDRANDw0PDg8NDw4PDg8NDw0QDQ8NEA0PDQ8ODw4PDSoOKg0QDQ8NDw4PDQ8OAAFHcToODw0rDQ8NEA0PDQ8ODw0QDQ8NEA0PDRANDw0rDQ8NEA0PDg8NDw4PDQ8NKw0rDSsNDw0QDSoNEA0PDRANDw0QDQ8ODw0PDRANDw0QDQ8NEA0rDQ8NDw4PDQ8ODw0PDRANEA0PDSsNDw0rDSoODw0QDQ8NEA0PDRANDw0PDg8NKw0PDg8NKw0PDSsOKQ4PDRANDw0QDQ8NDw4PDQ8PDg0QDQ8NEA0PDRANDw0PDg8NEA0PDSsNKg4PDQ8ODw0PDg8NEA0PDRANDw0PDykNKw0QDQ8NEA0PDQ8ODw0qDg8NEA0PDg8ODg0QDQ8NEA4ODg8NDw8ODg4PDg4ODg8ODg4qDg8ODg4ODw4ODg8ODg4PDg8ODikPKQ4ODw4ODg8ODg8OKQ8pDg4PKQ4qDikPKQ4qDgANBQAAAAAAAAAAAAAAAA=='
      command_off: 'JgC8AXQ4Dw0QKA8NEA0PDRANDw0QDQ8NEA0PDRANDw0QKA8NEA0QDQ8NEA0PDRAMECgQKA8pDw0QDQ8oEA0PDRANDw0QDRANDw0QDBANDw0QDQ8NEA0QDQ8NEA0PDRAMEA0PDRANEA0PDRANDw0QDBANDw0QDRANDygQKBAMEA0PDRANDw0QAAFFcToODw0rDQ8NDw4PDQ8ODw0QDQ8ODw8NDw4PDQ8pEAwPDg8NEA0PDw4NDw0QKA8oECkPDQ8NECgPDg8NDw0QDQ8ODw0ODw0PDRANDw0PDg8NEA0PDg8NDw4PDQ8NEA0PDRANDw4PDSoODw0rDSoODw0QDQ8NDw4PDQ8ODw0PDg8NKw4ODg8NKg4PDSoPKQ0PDg8ODw0PDg8NDw4PDQ8NEA0PDg8NDw4PDQ8ODw0PDRANEA0PDSsNKg4PDQ8NEA0PDRANDw4PDQ8ODw0PDioNKg4PDg8NDw4PDQ8NEA0qDg8NEA0PDQ8ODw0PDg8NDw4PDRANDw0QDQ8NDw4PDQ8ODw0rDQ8ODw0PDg8NDw0QDQ8NEA0PDioNKw0PDw4NDw0PDg8ODw0qEA0PKQ8oDykPKBAoEAANBQAAAAAAAAAAAAAAAA=='
    bedroomtv:
      friendly_name: "BedroomTV"
      command_on: 'JgBmAJSPFBAVNRQ1FDUVEBQRFBEUERQQFTUUNRQ1FRAUERQRFBAVEBUQFDUVNBUQFRAVEBQRFDUVNBUQFRAUNRU1FDUUNRQABemUjxQ1FQAMOJSPFDUVAAw4lI8UNRUADDiTkBM2EwANBQAA'
      command_off: 'JgBmAJSPFBAVNRQ1FDUVEBQRFBEUERQQFTUUNRQ1FRAUERQRFBAVEBUQFDUVNBUQFRAVEBQRFDUVNBUQFRAUNRU1FDUUNRQABemUjxQ1FQAMOJSPFDUVAAw4lI8UNRUADDiTkBM2EwANBQAA'
- platform: command_line
  switches:
    weather:
      command_on: ''
      command_off: cvlc vlc://quit 
